# Generated by Django 3.0.5 on 2020-04-27 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stir', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cocktail',
            options={},
        ),
    ]
