# Generated by Django 3.0.5 on 2020-05-12 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stir', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cocktail',
            table='cocktails_2',
        ),
    ]
