# Generated by Django 3.0.5 on 2020-04-23 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stir', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cocktail',
            table=None,
        ),
    ]
