# Generated by Django 3.0.5 on 2020-05-12 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stir', '0002_auto_20200512_0857'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cocktail',
            options={'managed': False},
        ),
    ]
