# Generated by Django 3.0.5 on 2020-04-27 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stir', '0002_auto_20200427_2337'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cocktail',
            options={'managed': False},
        ),
    ]
