# Generated by Django 3.0.5 on 2020-04-23 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stir', '0003_auto_20200423_0409'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cocktail',
            table=None,
        ),
    ]
