# Generated by Django 3.0.5 on 2020-04-28 00:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stir', '0003_auto_20200427_2342'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cocktail',
            options={},
        ),
    ]
