# Generated by Django 3.0.5 on 2020-04-23 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stir', '0004_auto_20200423_0423'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cocktail',
            options={'managed': False},
        ),
    ]
