# Generated by Django 3.0.5 on 2020-04-28 00:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stir', '0004_auto_20200428_0005'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cocktail',
            options={'managed': False},
        ),
    ]
