# Generated by Django 3.0.5 on 2020-04-23 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stir', '0005_auto_20200423_0435'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cocktail',
            table='cocktails',
        ),
    ]
