# Generated by Django 3.0.5 on 2020-04-23 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stir', '0007_auto_20200423_0441'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cocktails',
        ),
    ]
