# Generated by Django 3.0.5 on 2020-04-23 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stir', '0009_cocktails'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cocktails',
            options={},
        ),
    ]
