# Generated by Django 3.0.5 on 2020-04-23 05:13

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stir', '0011_auto_20200423_0509'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cocktail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('ingredients', django.contrib.postgres.fields.jsonb.JSONField()),
                ('instructions', django.contrib.postgres.fields.jsonb.JSONField()),
                ('garnishes', django.contrib.postgres.fields.jsonb.JSONField()),
                ('glass', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'cocktails',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Cocktails',
        ),
    ]
