# Generated by Django 3.0.5 on 2020-07-07 06:20

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stir', '0003_auto_20200512_0900'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrambleUserProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='users.BrambleUser')),
            ],
        ),
        migrations.CreateModel(
            name='CocktailProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('views', models.PositiveIntegerField(default=1)),
                ('bookmarks', models.ManyToManyField(related_name='bookmarks', to='profiles.BrambleUserProfile')),
                ('cocktail', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='stir.Cocktail')),
                ('favorites', models.ManyToManyField(related_name='favorites', to='profiles.BrambleUserProfile')),
            ],
        ),
    ]
